ShoppingProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingProject.Data;
using ShoppingProject.Data.Models;
using ShoppingProject.Models;
using ShoppingProject.Services;

namespace ShoppingProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> All(ProductListingModel query)
        {

            ////Get the currently Logged-in User and all its properties - Id, Products, ProductsId, Wishlist, Wishlist Id
            //var user = await userManager.GetUserAsync(User);

            ////Get the wishlist of the logged-in user
            //var wishlist = _dbContext.Wishlists.Where(w => w.Products == user.Wishlist.Products);

            ////Get the products of the logged-in user
            //var userProducts = _dbContext.Products.Where(p => p.UserId == user.Id);

            int currPage = query.CurrentPage;
            int pageSize = 8;
            
            if (currPage <= 0)
            {
                currPage = 1;
            }
            int skipCount = (currPage - 1) * pageSize;

            var allProducts = await _productService.GetAll();
            var productsQuery = allProducts.AsQueryable();

            if (!string.IsNullOrWhiteSpace(query.Search))
            {
                productsQuery = productsQuery.Where(p =>
                p.Name.ToLower().Contains(query.Search.ToLower()));
            }

            if (!string.IsNullOrWhiteSpace(query.ProductType))
            {
                productsQuery = productsQuery.Where(p => p.ProductType == query.ProductType);
            }

            var products = productsQuery
                .OrderByDescending(pt => pt.Id)
                .Skip(skipCount)
                .Take(pageSize)
                .Select(p => new AllProductsForm
                {
                    Id = p.Id,
                    Name = p.Name,
                    Description = p.Description,
                    Price = p.Price,
                    ImageURL = p.ImageURL,
                    ProductType = p.ProductType
                })
                .ToList();

            allProducts = await _productService.GetAll();
            var productCategories = allProducts
                .Select(p => p.ProductType)
                .Distinct()
                .ToList();

            return View(new ProductListingModel
            {
                Products = products,
                Search = query.Search,
                ProductTypes = productCategories,
                CurrentPage = currPage
            });


        }
        
        //Get Method
        public IActionResult Add()
        {
            return View();
        }

        // Adds products to the Database 
        [Authorize(Roles = DataConstants.Role.Administrator)]
        [HttpPost]
        public IActionResult Add(AddProductForm product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            var productData = new Product
            {
                Name = product.Name,
                Description = product.Description,
                ImageURL = product.ImageURL,
                Price = product.Price,
                ProductType = product.ProductType
            };
            _productService.Add(productData);

            return RedirectToAction(nameof(All));
        }

        //GETS the product id and gives the user the option to change its attributes 
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _productService.GetById(id);
            
            if (productDetails == null)
            {
                return NotFound(); 
            }

            var productForm = new AddProductForm()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                Description = productDetails.Description,
                ImageURL = productDetails.ImageURL,
                Price = productDetails.Price,
                ProductType = productDetails.ProductType

            };

            return View(productForm);
        }

        //Post Method that updates the DB
        [Authorize(Roles = DataConstants.Role.Administrator)]
        [HttpPost]
        public async Task<IActionResult> Edit(AllProductsForm product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            var productData = await _productService.GetById(product.Id);

            if (productData == null)
            {
                return NotFound();
            }

            productData.Name = product.Name;
            productData.Description = product.Description;
            productData.ImageURL = product.ImageURL;
            productData.Price = product.Price;
            productData.ProductType = product.ProductType;

            await _productService.Update(productData);
            return RedirectToAction("All", "Product");
        }


        public async Task<IActionResult> Delete(int id)
        {
            var productDetails = await _productService.GetById(id);
            if (productDetails == null) return NotFound();
            var gosho = new AddProductForm()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                Description = productDetails.Description,
                ImageURL = productDetails.ImageURL,
                Price = productDetails.Price,
                ProductType = productDetails.ProductType

            };
            return View(gosho);
        }

        [Authorize(Roles = DataConstants.Role.Administrator)]
        [HttpPost("[action]")]
        public async Task<IActionResult> DeleteConfirmed([FromForm] int id)
        {
            var productDetails = await _productService.GetById(id);
            if (productDetails == null) return NotFound();

            await _productService.Delete(id);
            return RedirectToAction(nameof(All));
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var product = _productService.Details(id);

            if (product == null)
            {
                return BadRequest();
            }

            return View(product);
        }
    }
}

ShoppingProject/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingProject.Data;
using ShoppingProject.Data.Models;
using ShoppingProject.Models;

namespace ShoppingProject.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ShoppingDbContext dbContext;
        private readonly UserManager<User> userManager;

        public ShoppingCartController(ShoppingDbContext dbContext, UserManager<User> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        public async Task <IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);

            if (user.ShoppingCart == null)
            {
                user.ShoppingCart = new ShoppingCart();
            }

            return View(new UserViewModel(user.Id, user.Wishlist, user.ShoppingCart));
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(AllProductsForm product)
        {
            var user = await userManager.GetUserAsync(User);

            var shoppingCart = dbContext.ShoppingCarts
             .FirstOrDefault(w => user.Id == w.UserId);


            if (!ModelState.IsValid)
            {
                return View(product);
            }

            var savedProduct = dbContext.Products.FirstOrDefault(p => p.Id == product.Id);
            
            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    UserId = user.Id,
                };
                dbContext.Add(shoppingCart);
            }

            if (savedProduct == null)
            {
                return NotFound();
            }

            shoppingCart.Products.Add(savedProduct);

            await dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var user = await userManager.GetUserAsync(User);

            var cart = dbContext.ShoppingCarts.FirstOrDefault(w => w.User.Id == user.Id);

            if (cart == null)
            {
                cart = new ShoppingCart
                {
                    UserId = user.Id
                };

            }

            var savedProduct = cart.Products.FirstOrDefault(p => p.Id == id);

            if (savedProduct == null)
            {
                return NotFound();
            }


            cart.Products.Remove(savedProduct);

            await dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
    }
}

ShoppingProject/Controllers/WishlistController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingProject.Data;
using ShoppingProject.Data.Models;
using ShoppingProject.Models;
using ShoppingProject.Services;

namespace ShoppingProject.Controllers
{
    public class WishlistController : Controller
    {
        private readonly ShoppingDbContext _dbContext;
        private readonly UserManager<User> userManager;
       

        public WishlistController(ShoppingDbContext dbContext,
            UserManager<User> userManager
            )
        {
            _dbContext = dbContext;
            this.userManager = userManager;
            
        }

        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);

            if (user.Wishlist == null)
            {
                user.Wishlist = new Wishlist();
            }

            return View(new UserViewModel(user.Id, user.Wishlist, user.ShoppingCart));
        }

        [HttpPost]
        public async Task<IActionResult> AddToWishlist(AllProductsForm product)
        {
            User? user = await userManager.GetUserAsync(User);

            Wishlist? wishlist = _dbContext.Wishlists
             .FirstOrDefault(w => user.Id == w.UserId);


            if (!ModelState.IsValid)
            {
                return View(product);
            }

            Product? savedProduct = _dbContext.Products.FirstOrDefault(p => p.Id == product.Id);
            

            if (wishlist == null)
            {
                wishlist = new Wishlist
                {
                    UserId = user.Id,
                };
                _dbContext.Add(wishlist);
            }

            if (savedProduct == null)
            {
                return NotFound();
            }

            wishlist.Products.Add(savedProduct);
            
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromWishlist(int id)
        {
            User? user = await userManager.GetUserAsync(User);

            Wishlist? wishlist = _dbContext.Wishlists.FirstOrDefault(w => w.User.Id == user.Id);
            
            if (wishlist == null)
            {
                wishlist = new Wishlist
                {
                    UserId = user.Id,
                };

            }

            Product? savedProduct = wishlist.Products.FirstOrDefault(p => p.Id == id);

            if (savedProduct == null)
            {
                return NotFound();
            }
         

            wishlist.Products.Remove(savedProduct);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
    }
}

ShoppingProject/Views/Product/Add.cshtml
@model AddProductForm

@{
    ViewData["Title"] = "Add a new Product";
}

<div class="row">
    <div class="col-6 offset-3">
        <h2 class="heading-margin text-center">Add Product</h2>
        <form method="post" asp-action="Add">
            <div>
                <div>
                    <img src ="https://www.nme.com/wp-content/uploads/2020/06/ps5-credit-sie@2000x1270.jpg" id="ImageURLPreview" width="640" height="480" class="center" />
                </div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="PS4, Xbox One">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div>
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Best game ever !!">
                <span asp-validation-for="Description" class="small text-danger"></span>
        </textarea>
            </div>

            <div>
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" placeholder="Picture URL">
                <span asp-validation-for="ImageURL" class="small text-danger"></span>
            </div>
            <div>
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="$25.99">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductType">Product Type</label>
                <select asp-for="ProductType" class="form-control">
                    <option>Video Games</option>
                    <option>Books</option>
                    <option>Smartphones</option>
                    <option>Laptops</option>
                    <option>Movies</option>
                    <option>Music</option>
                </select>
                <input class="btn btn-outline-success" type="submit" value="Save" />
            </div>

        </form>
    </div>
</div>

@section Scripts{
<script>
    $("#ImageURL").on("change", function (){
       var output = document.getElementById('ImageURLPreview');
       output.src = $(this).val();
    })
</script>
}

ShoppingProject/Views/Product/All.cshtml
@inject SignInManager<User> SignInManager;
@inject UserManager<User> UserManager;
@model ProductListingModel
@{
    ViewData["Title"] = "All";
}
<form method="get">
    <div class="row mb-5">
        <div class="form-group col-md-4">
            <label asp-for="Search"></label>
            <input asp-for="Search" class="form-control" placeholder="PS4, Xbox One">
            <input class="btn btn-info" type="submit" value="Search" />
        </div>

        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="ProductType">Product Type</label>
                <select asp-for="ProductType" class="form-control">
                    <option>Video Games</option>
                    <option>Books</option>
                    <option>Smartphones</option>
                    <option>Laptops</option>
                    <option>Movies</option>
                    <option>Music</option>
                </select>

            </div>
        </div>
    </div>
</form>





<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="card mb-2 mx-2" style="width: 18rem;">
            <img src="@product.ImageURL" class="card-img-top" alt="@product.Name - @product.Price (@product.ProductType" )>
            <div class="card-body text-center">
                <h5 class="card-title text-center">@product.Name</h5>
                
                <a asp-controller="Product" asp-action="Details" asp-route-id=@product.Id class="btn btn-primary">Details</a>
                @if (User.IsInRole(DataConstants.Role.Administrator))
                {
                    <a asp-controller="Product" asp-action="Edit" asp-route-id=@product.Id class="btn btn-warning">Edit</a>
                    <a asp-controller="Product" asp-action="Delete" asp-route-id=@product.Id class="btn btn-danger">Delete</a>
                }
                <p class="card-text">$@product.Price</p>
            </div>
        </div>
    }
</div>


<div class="row">
    <div class="col-md-6">
        <a asp-controller="Product" asp-action="All" asp-route-CurrentPage="@(Model.CurrentPage-1)"><<</a>
    </div>
    <div class="col-md-6">
        <a asp-controller="Product" asp-action="All" asp-route-CurrentPage="@(Model.CurrentPage+1)">>></a>
    </div>
</div>

ShoppingProject/Views/Product/Delete.cshtml
@model AddProductForm

@{
    ViewData["Title"] = "Delete Product";
}

<div class="row">
    <div class="col-6 offset-3">
        <h2 class="heading-margin text-center">Delete Product</h2>


        <form method="post" asp-action="DeleteConfirmed" asp-controller="Product">

            <input asp-for="Id" hidden />
            <div>
                <img id="ImageURLPreview" class="center" />
            </div>
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" readonly>
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div>
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" readonly>
                <span asp-validation-for="Description" class="small text-danger"></span>
        </textarea>
            </div>
            <div>
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" readonly>
                <span asp-validation-for="ImageURL" class="small text-danger"></span>
            </div>
            <div>
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" readonly>
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductType">Product Type</label>
                <select asp-for="ProductType" disabled class="form-control">
                    <option>Video Games</option>
                    <option>Books</option>
                    <option>Smartphones</option>
                    <option>Laptops</option>
                    <option>Movies</option>
                    <option>Music</option>
                </select>
                </div>
                <input class="btn btn-outline-danger" type="submit" value="Delete" />
        </form>
    </div>
</div>
@section Scripts{
<script>
    $("#ImageURL").on("change", function (){
       var output = document.getElementById('ImageURLPreview');
       output.src = $(this).val();
    })
</script>
}

ShoppingProject/Views/Product/Details.cshtml
@model AllProductsForm

@{
    ViewData["Title"] = "Details";
}

<div class="col-md-4 text-center rounded mx-auto d-block">
    <div class="card mb-4 bgcolor-gray border-none">
        <img asp-for="@Model.ImageURL" src="@Model.ImageURL" class="card-img-top" alt="@Model.Name">
        <div class="card-body">
            <h5 asp-for="@Model.Name" class="card-title text-center">@Model.Name</h5>
            <p asp-for="@Model.Price" class="card-text text-center">Price: $@Model.Price</p>
            <p asp-for="@Model.ProductType" class="card-text text-center">Category: @Model.ProductType</p>
        </div>
        <div class="card mb-2 mt-2">
            <form method="post" asp-action="AddToWishlist">
                <input asp-action="AddToWishlist" asp-controller="Wishlist" asp-route-id="@Model.Id" class="btn btn-outline-success" type="submit" value="Add to Wishlist" />
                <input asp-for="@Model.Id" hidden />
                <input asp-for="@Model.Name" hidden />
                <input asp-for="@Model.ImageURL" hidden />
                <input asp-for="@Model.Description" hidden />
                <input asp-for="@Model.ProductType" hidden />
            </form>
            <form method="post" asp-action="AddToCart">
                <input asp-action="AddToCart" asp-controller="ShoppingCart" asp-route-id="@Model.Id" class="btn btn-outline-warning" type="submit" value="Add to Cart" />
                <input asp-for="@Model.Id" hidden />
                <input asp-for="@Model.Name" hidden />
                <input asp-for="@Model.ImageURL" hidden />
                <input asp-for="@Model.Description" hidden />
                <input asp-for="@Model.ProductType" hidden />
            </form>

        </div>
    </div>
</div>
<div class="text-center mb-3">
    <span asp-for="@Model.Description" STYLE="font-size:18.0pt">@Model.Description</span>
</div>

ShoppingProject/Views/Product/Edit.cshtml
@model AddProductForm

@{
    ViewData["Title"] = "Edit Product";
}
<form method="post" asp-controller="Product" asp-action="Edit">

    <input asp-for="Id" hidden />
    <div class="row">
        <div class="col-6 offset-3">
            <h2 class="heading-margin text-center">Edit Product</h2>
            <div>
                <img id="ImageURLPreview" class="center" />
            </div>
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="PS4, Xbox One">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>

            <div>
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Best game ever !!">
                <span asp-validation-for="Description" class="small text-danger"></span>
        </textarea>
            </div>

            <div>
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" placeholder="Picture URL">
                <span asp-validation-for="ImageURL" class="small text-danger"></span>
            </div>

            <div>
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="$25.99">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductType">Product Type</label>
                <select asp-for="ProductType" class="form-control">
                    <option>Video Games</option>
                    <option>Books</option>
                    <option>Smartphones</option>
                    <option>Laptops</option>
                    <option>Movies</option>
                    <option>Music</option>
                </select>
                <input class="btn btn-outline-warning" type="submit" value="Edit" />
            </div>

        </div>
    </div>
</form>

@section Scripts{
<script>
    $("#ImageURL").on("change", function (){
       var output = document.getElementById('ImageURLPreview');
       output.src = $(this).val();
    })
</script>
}